### ISSUE TITLE
ERROR MESSAGE: Cookies must be enabled to use GitHub.

### ISSUE THREAD

**Issue by claytonpbarrows** [ahadik/git_mover#3]
I'm trying to migrate an enterprise repo to github.com, but I'm getting the following error:
```
git_mover cbarrows$ python git-mover.py -sr https://github.mycompany.url -dr https://github.com -dun claytonpbarrows -dt GithubComUserToken enterpriseUserName enterpriseUserToken EnterpriseOrganization/Repo GithubComOrganization/Repo
STATUS CODE: 403
ERROR MESSAGE: Cookies must be enabled to use GitHub.
False
STATUS CODE: 403
ERROR MESSAGE: Cookies must be enabled to use GitHub.
False
STATUS CODE: 403
ERROR MESSAGE: Cookies must be enabled to use GitHub.
False
STATUS CODE: 403
ERROR MESSAGE: Cookies must be enabled to use GitHub.
False
STATUS CODE: 403
ERROR MESSAGE: Cookies must be enabled to use GitHub.
False
STATUS CODE: 403
ERROR MESSAGE: Cookies must be enabled to use GitHub.
False
STATUS CODE: 403
ERROR MESSAGE: Cookies must be enabled to use GitHub.
False
STATUS CODE: 404
ERROR MESSAGE: Not Found
Traceback (most recent call last):
  File "git-mover.py", line 245, in <module>
    main()
  File "git-mover.py", line 224, in main
    res = create_labels(labels, destination_root, destination_repo, destination_credentials)
  File "git-mover.py", line 115, in create_labels
    for existing_label in check_labels:
TypeError: 'bool' object is not iterable
```
Any suggestions?

**Comment by claytonpbarrows** [comment]
ahh... removing the `-dr https://github.com` argument to make the destinationRepo point to `https://api.github.com` solved my issue.
